"""Add shelf_life column to product table

Revision ID: c5194d2a5f54
Revises: 545bae4b1811
Create Date: 2025-11-17 08:42:04.026560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5194d2a5f54'
down_revision = '545bae4b1811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('shelf_life')

    # ### end Alembic commands ###
